server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
stiger:
  frame:
    debug-mode: true
  admin:
    rabc:
      default-users:
        super-admin-username: admin
        super-admin-password: admin123456
  oss:
    minio:
      active: true
      access-key: test
      secret-key: test123456
      endpoint: http://127.0.0.1:9000/
    aliyun:
      active: true
      endpoint: oss-cn-shanghai.aliyuncs.com
      access-key-id: 1111111111111
      access-secret: 1111111111111
  sms:
    aliyun:
      access-key-id: 1111111111111
      access-secret: 1111111111111
