server:
  servlet:
    context-path: /stigerAdmin
  forward-headers-strategy: framework
spring:
  profiles:
    active: dev
  application:
    name: stiger-admin-manager
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: record_status
      logic-delete-value: N
      logic-not-delete-value: Y
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
stiger:
  admin:
    layui:
      init:
        logo-info:
          title: STiger Admin
          image-url: ${server.servlet.context-path}/images/logo.png
        multi-module: false
