server:
  servlet:
    context-path: /stigerAdmin
spring:
  profiles:
    active: dev
  application:
    name: stiger-admin-manager
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: record_status
      logic-delete-value: N
      logic-not-delete-value: Y
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
stiger.admin:
  init:
    logo-info:
      title: STiger Admin
      image-url: ${server.servlet.context-path}/images/logo.png
    multi-module: false
