server:
  port: 8080
  servlet:
    context-path: /stigerPay
  forward-headers-strategy: framework
spring:
  profiles:
    active: dev
  application:
    name: stiger-pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
mybatis-plus:
  global-config:
    banner: false
#    db-config:
#      logic-delete-field: record_status
#      logic-delete-value: N
#      logic-not-delete-value: Y
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl